;;
;; @author naoiwata
;; SICP Chapter1
;; q-1.15
;;

(define (cube x)
	(* x x x))

(define (p x)
	(- (* 3 x) (* 4 (cube x))))

(define (sine angle)
	(if (not (> (abs angle) 0.1))
		angle
		(p (sine (/ angle 3.0)))))

;; a) How many times is the procedure p applied when (sine 12.15) is evaluated?
(sine 12.15)
;-0.39980345741334

(sine 12.15)
(p (sine 4.05))
(p (p (sine 1.35)))
(p (p (p (sine 0.45))))
(p (p (p (p (sine 0.15)))))
(p (p (p (p (p (sine 0.05))))))
; 5 times

;; b) What is the order of growth in space and number of steps (as a function of a) used by the process generated by the sine procedure when (sine a) is evaluated?
;; see naoiwata.blogspot.com

;; END